# -----------------------------------------------------------------------------
# template-glue.yaml
# -----------------------------------------------------------------------------
# This CloudFormation template defines AWS Glue jobs and related resources for
# the ETL pipeline. It includes:
#
# - GlueLogGroup: A CloudWatch Log Group for Glue job output logs.
# - rGlueJobTransforma: A Glue job for the transformation step, running the
#   transform.py script from S3.
# - rGlueJobDataQuality: A Glue job for the data quality/cleaning step, running
#   the quality.py script from S3.
#
# Each job is configured with its script location, Glue version, arguments,
# IAM role, and worker settings. The IAM role is passed as a parameter.
# -----------------------------------------------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Description: Defining the glue jobs.

Parameters:
    roleglue:
        Type: String

Resources:
  GlueLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws-glue/jobs/output"

  rGlueJobTransforma:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: 3
        ScriptLocation: "s3://data-clouders-project/code/transform.py"
      GlueVersion: "4.0"
      DefaultArguments:
        "--job-language": "python"
        "--job-bookmark-option": "job-bookmark-enable"
        "--spark-event-logs-path": "s3://data-clouders-project/code/"
        "--enable-spark-ui": "true"
        "--enable-glue-datacatalog": "true"  
        "--enable-metrics": "true"           
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 1
      Name: GlueTransform
      Role: !Ref roleglue
      WorkerType: Standard
      NumberOfWorkers: 1

  rGlueJobDataQuality:
      Type: AWS::Glue::Job
      Properties:
        Command:
          Name: glueetl
          PythonVersion: 3
          ScriptLocation: "s3://data-clouders-project/code/quality.py"
        GlueVersion: "4.0"
        DefaultArguments: 
          "--job-language": "python"
          "--job-bookmark-option": "job-bookmark-enable"
          "--spark-event-logs-path": "s3://data-clouders-project/code/"
          "--enable-spark-ui": "true"
          "--enable-glue-datacatalog": "true"  
          "--enable-metrics": "true" 
        ExecutionProperty:
          MaxConcurrentRuns: 2
        MaxRetries: 1
        Name: GlueQuality
        Role: !Ref roleglue
        WorkerType: Standard
        NumberOfWorkers: 1